<a href="https://colab.research.google.com/github/evelynda1985/DataScience/blob/master/MultiLinearRegSklearnStandarizationPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Relevant Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

# Load the data

In [2]:
import google.colab
google.colab.files.upload()

Saving 1.02.MultipleLinearRegression.csv to 1.02.MultipleLinearRegression.csv


{'1.02.MultipleLinearRegression.csv': b'SAT,GPA,"Rand 1,2,3"\r\n1714,2.40,1\r\n1664,2.52,3\r\n1760,2.54,3\r\n1685,2.74,3\r\n1693,2.83,2\r\n1670,2.91,1\r\n1764,3.00,2\r\n1764,3.00,1\r\n1792,3.01,2\r\n1850,3.01,3\r\n1735,3.02,3\r\n1775,3.07,2\r\n1735,3.08,1\r\n1712,3.08,3\r\n1773,3.12,2\r\n1872,3.17,2\r\n1755,3.17,3\r\n1674,3.17,2\r\n1842,3.17,3\r\n1786,3.19,3\r\n1761,3.19,3\r\n1722,3.19,3\r\n1663,3.20,3\r\n1687,3.21,1\r\n1974,3.24,1\r\n1826,3.28,1\r\n1787,3.28,1\r\n1821,3.28,3\r\n2020,3.28,1\r\n1794,3.28,2\r\n1769,3.28,1\r\n1934,3.28,1\r\n1775,3.29,1\r\n1855,3.29,3\r\n1880,3.29,2\r\n1849,3.31,2\r\n1808,3.32,3\r\n1954,3.34,3\r\n1777,3.37,3\r\n1831,3.37,2\r\n1865,3.37,3\r\n1850,3.38,1\r\n1966,3.38,3\r\n1702,3.39,1\r\n1990,3.39,1\r\n1925,3.40,2\r\n1824,3.40,2\r\n1956,3.40,1\r\n1857,3.41,1\r\n1979,3.41,3\r\n1802,3.41,3\r\n1855,3.42,1\r\n1907,3.42,2\r\n1634,3.42,2\r\n1879,3.44,1\r\n1887,3.47,1\r\n1730,3.47,2\r\n1953,3.47,1\r\n1781,3.47,2\r\n1891,3.48,2\r\n1964,3.49,1\r\n1808,3.49,3\r\n1893,3

In [3]:
data = pd.read_csv('1.02.MultipleLinearRegression.csv')
data

SAT   GPA  Rand 1,2,3
0   1714  2.40           1
1   1664  2.52           3
2   1760  2.54           3
3   1685  2.74           3
4   1693  2.83           2
..   ...   ...         ...
79  1936  3.71           3
80  1810  3.71           1
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

[84 rows x 3 columns]

In [4]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

# Create Multiple Linear Regression

# Declare the dependant and independant variable

In [5]:
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

# Standardization

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
scaler = StandardScaler()

In [8]:
scaler.fit(x)

StandardScaler()

In [9]:
x_scaled = scaler.transform(x)

In [10]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

# Regression with scaled features

In [11]:
reg = LinearRegression()
reg.fit(x_scaled, y)

LinearRegression()

In [12]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [13]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [14]:
reg.intercept_

np.float64(3.330238095238095)

# Creating a Summaty Table

In [20]:
reg_summary = pd.DataFrame([['Intercept'], ['SAT'], ['Rand 1,2,3']], columns=['Features'])
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [21]:
#Weight = Coeficients
reg_summary

Features   Weights
0   Intercept  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

In [22]:
# ML the word Intercept = Bias
reg_summary = pd.DataFrame([['Bias'], ['SAT'], ['Rand 1,2,3']], columns=['Features'])
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [23]:
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

In [24]:
#When we perform feature scalilng, we don't care if a useless variable is there or not
#Either although is better to remove them

# Making Predictions with the standardized coefficients (weights)

In [25]:
new_data = pd.DataFrame(data=[[1700,2],[1800,1]],columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [26]:
#Those values doesn't make sense, there are not a valid GPA
#This happens because the standarization
reg.predict(new_data)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([295.39979563, 312.58821497])

In [28]:
#The new data frame should be arranged in the same way
# and also must be standarized in the same way
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [31]:
#this GPA makem more sense
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

# What is we remove the 'Random 1,2,3' variable/feature?

In [32]:
#nothing should change but let's see
reg_simple = LinearRegression()
x_simple_matrix = x_scaled[:,0].reshape(-1,1)
reg_simple.fit(x_simple_matrix,y)

LinearRegression()

In [33]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])

In [34]:
#Like you can see the values with the variable and withouth the variable
#get the same GPA, the standaridarzation helps to give a minimize the value of useless variables
#with Random variable
#array([3.09051403, 3.26413803])
#withouth a random variable
#array([3.08970998, 3.25527879])