<a href="https://colab.research.google.com/github/evelynda1985/DataScience/blob/master/sklearnMultipleLinearRegressionFeatureSelectionPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Adjusted R-squared - Exercise Solution

Using the code from the lecture, create a function which will calculate the adjusted R-squared for you, given the independent variable(s) (x) and the dependent variable (y).

Check if you function is working properly.

Solution at the bottom.

## Import the relevant libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

## Load the data

In [3]:
import google.colab
google.colab.files.upload()

Saving 1.02.MultipleLinearRegression.csv to 1.02.MultipleLinearRegression.csv


{'1.02.MultipleLinearRegression.csv': b'SAT,GPA,"Rand 1,2,3"\r\n1714,2.40,1\r\n1664,2.52,3\r\n1760,2.54,3\r\n1685,2.74,3\r\n1693,2.83,2\r\n1670,2.91,1\r\n1764,3.00,2\r\n1764,3.00,1\r\n1792,3.01,2\r\n1850,3.01,3\r\n1735,3.02,3\r\n1775,3.07,2\r\n1735,3.08,1\r\n1712,3.08,3\r\n1773,3.12,2\r\n1872,3.17,2\r\n1755,3.17,3\r\n1674,3.17,2\r\n1842,3.17,3\r\n1786,3.19,3\r\n1761,3.19,3\r\n1722,3.19,3\r\n1663,3.20,3\r\n1687,3.21,1\r\n1974,3.24,1\r\n1826,3.28,1\r\n1787,3.28,1\r\n1821,3.28,3\r\n2020,3.28,1\r\n1794,3.28,2\r\n1769,3.28,1\r\n1934,3.28,1\r\n1775,3.29,1\r\n1855,3.29,3\r\n1880,3.29,2\r\n1849,3.31,2\r\n1808,3.32,3\r\n1954,3.34,3\r\n1777,3.37,3\r\n1831,3.37,2\r\n1865,3.37,3\r\n1850,3.38,1\r\n1966,3.38,3\r\n1702,3.39,1\r\n1990,3.39,1\r\n1925,3.40,2\r\n1824,3.40,2\r\n1956,3.40,1\r\n1857,3.41,1\r\n1979,3.41,3\r\n1802,3.41,3\r\n1855,3.42,1\r\n1907,3.42,2\r\n1634,3.42,2\r\n1879,3.44,1\r\n1887,3.47,1\r\n1730,3.47,2\r\n1953,3.47,1\r\n1781,3.47,2\r\n1891,3.48,2\r\n1964,3.49,1\r\n1808,3.49,3\r\n1893,3

In [4]:
data = pd.read_csv('1.02.MultipleLinearRegression.csv')
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [5]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

## Create the multiple linear regression

### Declare the dependent and independent variables

In [6]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

### Regression itself

In [7]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [8]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [9]:
reg.intercept_

np.float64(0.29603261264909486)

### Calculating the R-squared

In [10]:
reg.score(x,y)

0.4066811952814283

### Formula for Adjusted R^2

$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [11]:
x.shape

(84, 2)

In [12]:
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]

adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.3920313482513401

### Adjusted R^2 function

In [13]:
# There are different ways to solve this problem
# To make it as easy and interpretable as possible, we have preserved the original code
def adj_r2(x,y):
    r2 = reg.score(x,y)
    n = x.shape[0]
    p = x.shape[1]
    adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
    return adjusted_r2

In [14]:
# Here's the result
adj_r2(x,y)

0.3920313482513401

# Feature selection

In [15]:
#How to identify when a variable is useful or not
# with math stast we could figured out with p-|t| (p-value) > 0.05 the variable is not useful
from sklearn.feature_selection import f_regression

In [16]:
#The results are 2 arrays
# First array is for F-statistics
# Second array for p-values
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [19]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [20]:
p_values.round(3)

array([0.   , 0.676])