<a href="https://colab.research.google.com/github/evelynda1985/DataScience/blob/master/TrainTestPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [3]:
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

# Split the data

In [6]:
#First array is the training array
# Second one is the testing array
train_test_split(a)

[array([  2,  28,  32,  31,  45,  10,  20,  75,  68,  14,  51,  80,  64,
         26,   7,  53,  37,  48,  76,  89,  36,  94,  81,  41,  27,  19,
         90,  13,  65,  52,  73,  42,  62,  54,  59,   4,  24,  63,   8,
         44,  57,  15,  34,  84,   1,  93,  83,  39,  55,  70,  58,  99,
         46,  96,  86,  30,  74,  50,   3,  85,  71,  40,  35,  43,  16,
         29,  98,  60,  72, 100,  25,  22,  95,  33,  87]),
 array([79, 66, 12, 56, 69, 18, 82, 23, 88, 38,  5,  9, 11, 92, 78, 47, 91,
        61, 67, 17,  6, 21, 77, 97, 49])]

In [7]:
a_train, a_test = train_test_split(a)

# Explore the result

In [11]:
#this is the lenght/size of each array
#train has 75 and test 25
a_train.shape, a_test.shape

((75,), (25,))

In [12]:
a_train

array([ 93,  78,  37,  85,  80,  16,  44,  86,  49,  87,  61,  27,  79,
        97,  11,  40,  90,  60,  34,  55,  41,  50,  72,  95,  81,  70,
        10,  15,  65,  17,  58,  23,  19,  94,  51,  35,  46,  63,  12,
        20,   1,  62,  89,  22,  32,  92,  84,  66,  77,  47,  56,   4,
        42,  57,  76, 100,  98,  75,  91,  45,  33,  71,   8,   5,  74,
        18,   2,  13,  83,  68,  64,  73,   6,  26,  48])

In [10]:
a_test

array([14, 88, 29, 67, 21, 39, 43, 36, 38, 82, 59, 53, 25,  7, 28,  3,  9,
       69, 52, 96, 54, 24, 31, 99, 30])

In [17]:
#if we want to change the data size
#data is shuffle, so we can turn off that
a_train, a_test = train_test_split(a, test_size=0.2, shuffle = False)
a_train.shape, a_test.shape

((80,), (20,))

In [18]:
a_train

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [19]:
a_test

array([ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100])

In [20]:
#Assure the suffle data doesn't change is time --> random_state = 42
a_train, a_test = train_test_split(a, test_size=0.2, shuffle = True, random_state=42)
a_train.shape, a_test.shape

((80,), (20,))

In [21]:
a_train

array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])

In [22]:
a_test

array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
       78, 13, 32])

In [25]:
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size=0.2, random_state=365)

In [26]:
a_train

array([ 25,  32,  99,  73,  91,  66,   3,  59,  94,   1,   8,  15,  90,
        54,  31,  20,  77,  82,  30,  35,  95,  42,  38,   7,  11,  50,
        21,  48,   2,  17,  10,  58,  68,  43,  41,  16,  88,  72,  79,
       100,  80,  39,  24,  86,  22,  23,  62,  76,  18,  47,  55,  26,
        60,  19,  71,  64,  51,  63,  65,  28,  12,  78,  13,  44,  75,
        87,  40,   4,  29,  49,  37,  57,  27,  74,   6,  45,  92,  34,
        53,  83])

In [27]:
a_test

array([ 9, 69, 81, 56, 33, 93, 84, 61, 46, 89, 85, 67, 97,  5, 70, 36, 98,
       96, 14, 52])

In [28]:
b_train

array([525, 532, 599, 573, 591, 566, 503, 559, 594, 501, 508, 515, 590,
       554, 531, 520, 577, 582, 530, 535, 595, 542, 538, 507, 511, 550,
       521, 548, 502, 517, 510, 558, 568, 543, 541, 516, 588, 572, 579,
       600, 580, 539, 524, 586, 522, 523, 562, 576, 518, 547, 555, 526,
       560, 519, 571, 564, 551, 563, 565, 528, 512, 578, 513, 544, 575,
       587, 540, 504, 529, 549, 537, 557, 527, 574, 506, 545, 592, 534,
       553, 583])

In [29]:
b_test

array([509, 569, 581, 556, 533, 593, 584, 561, 546, 589, 585, 567, 597,
       505, 570, 536, 598, 596, 514, 552])